# Generated by Django 4.2 on 2025-02-21 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('durada', models.IntegerField(help_text='Durada en minuts')),
                ('descripcio', models.TextField()),
                ('genere', models.CharField(max_length=100)),
                ('data_estrena', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacitat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sales.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sales.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('tipus', models.CharField(choices=[('standard', 'EstÃ ndard'), ('premium', 'Premium')], max_length=10)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='butaques', to='sales.sala')),
            ],
            options={
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preu', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('butaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrades', to='sales.butaca')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrades', to=settings.AUTH_USER_MODEL)),
                ('sessio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrades', to='sales.sessio')),
            ],
            options={
                'unique_together': {('sessio', 'butaca')},
            },
        ),
    ]
