# Generated by Django 4.2 on 2025-02-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='butaca',
            options={'verbose_name_plural': 'Butaques'},
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'verbose_name_plural': 'Entrades'},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'verbose_name_plural': 'Pel·lícules'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='sessio',
            options={'verbose_name_plural': 'Sessions'},
        ),
    ]
