# Generated by Django 4.2 on 2025-02-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_butaca_options_alter_entrada_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'verbose_name': 'Pel·lícula', 'verbose_name_plural': 'Pel·lícules'},
        ),
    ]
